"""
pages/3_Model_Info.py
========================
Model Information page: training dataset, training date, algorithm,
vectorizer, vocabulary size, accuracy/F1, and the full evaluation artifacts
generated by the Phase 1 notebook.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd
import streamlit as st

from utils.model_utils import ModelLoadError, load_artifacts, warmup
from utils.ui import case_card_close, case_card_open, eyebrow, inject_theme, render_sidebar

st.set_page_config(page_title="Model Info | Fake News Intelligence", page_icon="ℹ️", layout="wide")
inject_theme()


@st.cache_resource(show_spinner="Loading model artifacts...")
def get_artifacts():
    artifacts = load_artifacts(models_dir="models", reports_dir="reports")
    warmup(artifacts)
    return artifacts


try:
    artifacts = get_artifacts()
except ModelLoadError as exc:
    st.error(f"Model artifacts not found: {exc}")
    st.stop()

render_sidebar(artifacts)

metrics = artifacts.evaluation_metrics
test_metrics = metrics.get("test_metrics", {})
vec_config = metrics.get("vectorizer_config", {})
comparison = metrics.get("model_comparison", [])

eyebrow("Case File")
st.markdown("# Model Information")
st.markdown("Every field below is read directly from `reports/evaluation_metrics.json`, produced by the Phase 1 training notebook.")

# --------------------------------------------------------------------------
# Top-line facts
# --------------------------------------------------------------------------
col1, col2, col3, col4 = st.columns(4)
col1.metric("Algorithm", metrics.get("best_model_name", "N/A"))
col2.metric("Test Accuracy", f"{test_metrics.get('accuracy', 0) * 100:.1f}%")
col3.metric("Test F1-Score", f"{test_metrics.get('f1_score', 0):.4f}")
col4.metric("ROC-AUC", f"{test_metrics.get('roc_auc', 0):.4f}")

st.markdown("---")

info_col, perf_col = st.columns(2)

with info_col:
    case_card_open("Training Details")
    st.write(f"**Training generated at:** {metrics.get('generated_at_utc', 'N/A')}")
    st.write(f"**Total dataset size:** {metrics.get('dataset_size', 0):,} articles")
    st.write(f"**Training rows:** {metrics.get('train_size', 0):,}")
    st.write(f"**Test rows:** {metrics.get('test_size', 0):,}")
    st.write("**Dataset source:** Kaggle 'Fake News' competition (id, title, author, text, label)")
    case_card_close()

    case_card_open("Vectorizer Configuration")
    st.write(f"**Type:** TF-IDF")
    st.write(f"**N-gram range:** {tuple(vec_config.get('ngram_range', ['?', '?']))}")
    st.write(f"**Max features:** {vec_config.get('max_features', 'N/A'):,}")
    st.write(f"**min_df:** {vec_config.get('min_df', 'N/A')}")
    st.write(f"**max_df:** {vec_config.get('max_df', 'N/A')}")
    st.write(f"**Vocabulary size:** {vec_config.get('vocabulary_size', 0):,}")
    case_card_close()

with perf_col:
    case_card_open("Held-out Test Performance")
    perf_df = pd.DataFrame({
        "Metric": ["Accuracy", "Precision", "Recall", "F1-Score", "ROC-AUC", "PR-AUC"],
        "Score": [
            test_metrics.get("accuracy", 0), test_metrics.get("precision", 0),
            test_metrics.get("recall", 0), test_metrics.get("f1_score", 0),
            test_metrics.get("roc_auc", 0), test_metrics.get("pr_auc", 0),
        ],
    })
    st.dataframe(perf_df, width='stretch', hide_index=True)
    case_card_close()

    case_card_open("Confusion Matrix")
    st.write(f"**False Positives** (real flagged as fake): {metrics.get('false_positive_count', 'N/A')}")
    st.write(f"**False Negatives** (fake missed): {metrics.get('false_negative_count', 'N/A')}")
    cm = metrics.get("confusion_matrix")
    if cm:
        cm_df = pd.DataFrame(cm, index=["Actual: Real", "Actual: Fake"], columns=["Pred: Real", "Pred: Fake"])
        st.dataframe(cm_df, width='stretch')
    case_card_close()

st.markdown("---")

# --------------------------------------------------------------------------
# Full model comparison table
# --------------------------------------------------------------------------
eyebrow("Model Bake-off")
st.markdown("### All Candidate Models (from the Phase 1 notebook)")
if comparison:
    st.dataframe(pd.DataFrame(comparison), width='stretch', hide_index=True)
else:
    st.info("No model comparison data found.")

st.markdown("### Best Hyperparameters (RandomizedSearchCV)")
st.json(metrics.get("best_params", {}))

st.markdown("---")

# --------------------------------------------------------------------------
# Notebook charts, embedded directly (real, generated images -- not redrawn)
# --------------------------------------------------------------------------
eyebrow("Supporting Evidence")
st.markdown("### Charts from the Training Notebook")

reports_dir = Path("reports")
chart_files = {
    "Class Distribution": "class_distribution.png",
    "Model Comparison": "model_comparison.png",
    "Confusion Matrix": "confusion_matrix.png",
    "ROC / Precision-Recall Curves": "roc_pr_curves.png",
    "Feature Importance": "feature_importance.png",
}

chart_cols = st.columns(2)
for i, (title, fname) in enumerate(chart_files.items()):
    path = reports_dir / fname
    with chart_cols[i % 2]:
        case_card_open(title)
        if path.exists():
            st.image(str(path), width='stretch')
        else:
            st.caption("Chart not found — re-run the Phase 1 notebook to regenerate it.")
        case_card_close()

st.markdown("---")
st.caption(
    "About this model: trained and evaluated in `notebooks/01_fake_news_intelligence.ipynb`. "
    "Version 1.0.0."
)
